# --- !Ups

create table "claims" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "id_user"   int not null,
  "id_claims" int not null
);

# --- !Downs

drop table "claims" if exists;

