# --- !Ups

--
CREATE DATABASE IF NOT EXISTS TOLLGATE default charset utf8mb4 COLLATE utf8mb4_general_ci;

-- Created table 'clients' in database
CREATE TABLE `CLIENTS` (

  ID                INT             NOT NULL AUTO_INCREMENT,
  CLIENT_ID         VARCHAR(36)     NOT NULL UNIQUE,
  SECRET            VARCHAR(30)     NOT NULL,
  NAME              VARCHAR(50)     NOT NULL,
  EFFECTIVE_FROM    DATE            NOT NULL,
  EXPIRED_AFTER     DATE            NOT NULL,
  CREATED_AT        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;


-- Example:
-- INSERT INTO CLIENTS( CLIENT_ID, SECRET, NAME, EFFECTIVE_FROM, EXPIRED_AFTER ) VALUES ( uuid(), '123456', 'Airbnb', '20190317', '20190317' );

-- Created table 'access_tokens' in database
CREATE TABLE `ACCESS_TOKENS` (

  ID                INT             NOT NULL AUTO_INCREMENT,
  TOKEN             VARCHAR(36)     NOT NULL,
  ISSUED_AT         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRED_AFTER     TIMESTAMP       NOT NULL,
  IS_EXPIRED        ENUM('Y', 'N')  NOT NULL,
  ID_CLIENT         INT             NOT NULL DEFAULT 0,
  CREATED_AT        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;


# --- !Downs

DROP TABLE    "CLIENTS"         IF EXISTS;
DROP TABLE    "ACCESS_TOKENS"   IF EXISTS;
DROP DATABASE "TOLLGATE"        IF EXISTS;


