# --- !Ups

CREATE TABLE "T_ACCESS_TOKEN"  {
    "ID"                bigint generated by default as identify(start with 1) not null primary key,
    "TOKEN"             int not null,
    "ISSUED_AT"         timestamp not null,
    "EXPIRED_AFTER"     timestamp not null
}

CREATE TABLE "T_REFRESH_TOKEN" {
    "ID"                bigint generated by default as identify(start with 1) not null primary key,
    "TOKEN"             int not null,
    "ISSUED_AT"         timestamp not null,
    "EXPIRED_AFTER"     timestamp not null
}

CREATE TABLE "T_CLIENT" {

    "ID"                bigint generated by default as identify(start with 1) not null primary key,
    "CLIENT_ID"         int not null,
    "CLIENT_SECARET"    int not null,
    "CREATED_AT"        timestamp not null,
    "EXPIRED_AFTER"     timestamp not null

}

CREATE TABLE "T_CLAIM" (
  "ID"              bigint generated by default as identity(start with 1) not null primary key,
  "CLAIM"           varchar not null
);

# --- !Downs

DROP TABLE "T_ACCESS_TOKEN"  IF EXISTS;
DROP TABLE "T_REFRESH_TOKEN" IF EXISTS;

DROP TABLE "T_CLAIM"         IF EXISTS;
DROP TABLE "T_CLIENT"        IF EXISTS;

